# Generated by Django 5.0.2 on 2024-02-29 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_note_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='summary',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.DeleteModel(
            name='BlogPost',
        ),
    ]
