# Generated by Django 5.0.2 on 2024-03-05 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_note_summary_delete_blogpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='analysis',
            field=models.TextField(blank=True),
        ),
    ]
