# Generated by Django 5.0.2 on 2024-04-07 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_notegroup_note_groups'),
        ('notes', '0005_notegroup_note_groups_userprofile'),
    ]

    operations = [
    ]
