# Generated by Django 5.0.4 on 2024-04-23 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0006_note_pinned'),
        ('notes', '0006_remove_note_analysis_remove_note_last_modified_and_more'),
    ]

    operations = [
    ]
